name: Collect Hydra Results

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  GH_PUB_KEY:
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  GH_BOT_ACC_EMAIL:
    41898282+github-actions[bot]@users.noreply.github.com
  GH_BOT_ACC_NAME:
    github-actions[bot]

jobs:
  collect:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY

      - name: setup git
        run: |
          git config --local user.email $GH_BOT_ACC_EMAIL
          git config --local user.name $GH_BOT_ACC_NAME
          git remote add ssh "git@github.com:${{ github.repository }}"

          git fetch origin
          git checkout results

      - name: Merge main changes
        run: |
           git pull --no-rebase origin iedame

      - name: Migrate result files to trunk directory
        run: |
          files=(
            "1-post-cleanup.csv"
            "2-failures.csv"
            "3-failures-aarch64-darwin.csv"
            "3-failures-aarch64-linux.csv"
            "3-failures-x86_64-darwin.csv"
            "3-failures-x86_64-linux.csv"
            "4-failures-packed.csv"
            "concerned-failures.json"
            "job_id"
          )

          moved=false

          for file in "${files[@]}"; do
            if [ -f "results/$file" ]; then
              echo "Found $file, moving to results/trunk"
              mkdir -p results/trunk
              git mv "results/$file" "results/trunk/$file"
              moved=true
            fi
          done

          if [ "$moved" = true ]; then
            git commit -m "migrate to trunk directory"
          fi

      - name: Back prev results
        run: |
          for branch in trunk staging-next; do
            mv results/$branch/concerned-failures.json previous-$branch.json || echo [] > previous-$branch.json
          done

      - name: Run collect script
        run: |
          nix run github:${{ github.repository }}

      - name: Open issue for new build failures
        run: |
         GH_REPOSITORY=${{ github.repository }} \
           GH_TOKEN=${{ secrets.GITHUB_TOKEN }} python create-issues.py

      - name: Cleanup
        run: |
          rm previous-*.json

      - name: Commit results
        run: |
          git add results/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Hydra results"
            git push ssh results --force
          fi
